### ISSUE TITLE
Referrers not available after Flush, need to refresh

### ISSUE THREAD

**Issue by dantleech** [doctrine/phpcr-odm#621]
It *seems* that referrers are not available on a newly created document after a flush, calling `refresh` on the same document after the flush makes them available.

````php
            $this->documentManager->persist($document); // new document
            $this->documentManager->flush();

            echo $document->getRoutes()->count(); // 0

            $this->documentManager->refresh($document);
            echo $document->getRoutes()->count(); // > 0
````

**Comment by dantleech** [comment]
Hmm, actually I think we have seen this before, the issue is that the referrers are created in an event listener after the flush, so we would need to find any objects in the UOW which are referrered to by the newly created objects and update their references accordingly.

**Comment by dbu** [comment]
did you see these two sections in the doc?
http://doctrine-phpcr-odm.readthedocs.org/en/latest/reference/association-mapping.html#referrers-to-inverse-the-reference-relation
http://doctrine-phpcr-odm.readthedocs.org/en/latest/reference/association-mapping.html#new-collections-after-flushing

i think we discussed that at length at some point, but can't find the discussion anymore. the problem is that we would need to go through all stored documents and check if you need to update. also, the orm does not automatically update the non-owning side of relations on flushes either.

**Comment by dantleech** [comment]
hmm ok. I also remember that discussion. It means I need to do something like:

````php
        $routes = $page->getRoutes();

        if (0 === $routes->count()) {
            $this->documentManager->refresh($page);
        }

        $routes = $page->getRoutes();

        if (0 === $routes->count()) {
            throw new RouteNotFoundException(sprintf(
                'Page document at "%s" does not have any route objects associated with it',
                $page->getPath()
            ));
        }
````

Although I guess a solution would be to use the document manager itself to get the referrers.

**Comment by dbu** [comment]
FTR: doctrine orm is handling this the same. if you want up-to-date models, you need to set the relation on both model instances. i'd consider that the proper implementation rather than refresh (which only works after flushing).
