### ISSUE TITLE
Support for "Indexed Associations" as in the Doctrine ORM

### ISSUE THREAD

**Issue by koemeet** [doctrine/phpcr-odm#701]
I could not find a way to make a `reference-many` association indexed by a specific field or it's node name. In the Doctrine ORM there is something like the `indexBy` mapping, that you can use to get an associative collection. Is support for this in PHPCR ODM something that might happen?

We could achieve this by adding the appropriate code to the `ReferenceManyCollection::initialize` method.

**Comment by dbu** [comment]
sounds like a useful feature. however, what happens if the index is not unique? using the full path of the target documents would be unique. the node name can not be guaranteed to be unique, and neither a field of a document.

why did you close #702, did it not work?

**Comment by steffenbrem** [comment]
Well I used that branch to fix the issue for me for now, making a PR was by accident. But if you like it I can reopen it.

The reason I only wanted the node name to be the index is because I am using the translations system from the `ResourceBundle` of Sylius. They require that the collection is indexed by it's locale. I wanted to avoid a different translation strategy for PHPCR documents and make it work the same way as translations do for ORM entities.

I am curious how a node name can be not unique in the same parent document? I have never been able to make a node at the same parent with the same name.

**Comment by dbu** [comment]
within the children collection, names indeed will be unique, and there it would make a ton of sense to index by name.

with references, you can reference arbitrary documents. if you reference /a/b/c and /b/b/c then both local names will be "c".
