### ISSUE TITLE
Binding string with apostrophe using QueryBuilder->literal() crash query

### ISSUE THREAD

**Issue by stopsopa** [doctrine/phpcr-odm#745]
Error like:

![image](https://cloud.githubusercontent.com/assets/3743506/26717678/2787bcb6-4776-11e7-9362-cf7f08a5448e.png)

When query is build like:

![image](https://cloud.githubusercontent.com/assets/3743506/26717395/28022952-4775-11e7-80f9-4f23f69e7967.png)

Fixed in my case:

![image](https://cloud.githubusercontent.com/assets/3743506/26717503/96994878-4775-11e7-8263-03ab51012134.png)

but i think it should do this automatically internally.
Or there should be method to bind explicitly data like in regular doctrine project:

http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/query-builder.html#binding-parameters-to-your-query

**Comment by dbu** [comment]
this looks like a bug in phpcr-utils: https://github.com/phpcr/phpcr-utils/blob/b222c2ad9f4772257106c77da8048f9ced5af111/src/PHPCR/Util/QOM/BaseSqlGenerator.php#L283

to narrow this down, could you edit that class in your local env to escape the single quote in what is returned, so we know its really that? do you maybe have time to work on fixing this? otherwise i will try to find some time in the next week.

**Comment by stopsopa** [comment]
Yep, i changed...
![image](https://user-images.githubusercontent.com/3743506/28120450-ff96b982-670f-11e7-9fc9-2d2590c6c919.png)
... and it seems to fix that too

**Comment by dbu** [comment]
fixed in https://github.com/phpcr/phpcr-utils/pull/224
