### ISSUE TITLE
Cannot remove nodes with autogenerated @Nodename

### ISSUE THREAD

**Issue by mreiche** [doctrine/phpcr-odm#754]
I have an abstract document:

```php
/**
 * @MappedSuperclass(
 *     referenceable=true,
 *     mixins={"mix:created", "mix:lastModified"}
 * )
 */
abstract class AbstractDocument {
	/**
	 * @Id
	 */
	private $id;
	/**
	 * @Uuid()
	 */
	private $uuid;
	/**
	 * @ParentDocument(cascade={"persist"})
	 */
	private $parent;
}
```

Which has no Nodename-property, which means, the local name and id were auto generated.
When removing such a document:

```php
$dm = $this->getDocumentManager();
$rootDoc = $dm->find(null,'/');
/** @var AbstractDocument[] $children */
$children = $rootDoc->getChildren();
foreach ($children as $child) {
    echo $child->getUuid()."\n";
    $dm->remove($child);
}
$dm->flush();
```

I get the following exception.
``Doctrine\ODM\PHPCR\PHPCRException: Cannot move/copy children by assignment as it would be ambiguous. Please use the DocumentManager::move() or PHPCR\Session::copy() operations for this: Topic@000000005c2f88550000000079d0359f (/454625409)``

Reference: https://stackoverflow.com/questions/46077197/doctrine-phpcr-how-to-remove-children-from-the-root-document/46077719

**Comment by dbu** [comment]
i think you can explicitly set the strategy even if you have a mapped nodename, to keep having generated ids. this might help as a workaround.

but this seems a bug in the code that calculates the diff. to narrow down the issue: does it only happen with direct children of the root node? or also deeper in the tree? can you test out what happens if you directly load a child and remove that, without loading the root? next step would be to write a failing test case and then try to find where in the UnitOfWork things get confused (smells like there is a problem with the parent's children collection still containing the removed document or something like that). can you dig further into it? i can't promise to find time very soon to work on it.
