### ISSUE TITLE
translator="attribute" in MetaData is NULL

### ISSUE THREAD

**Issue by henningborchers** [doctrine/phpcr-odm#763]
Hello,

i want to convert my document to a translatable with the command:
doctrine:phpcr:document:convert-translation
but get the exception:
Previous and current strategy are the same. To untranslate a document, you need to specify the previous translation strategy

I am using phpcr-odm version 1.4.2.

My translator is NULL in the ClassMetadata, but i configured my document with translator="attribute". I have cleared all caches.

```
<?php

namespace Drama\TestApp\CoreBundle\Document;

use Doctrine\ODM\PHPCR\Mapping\Annotations as PHPCR;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @PHPCR\Document(translator="attribute")
 */
class BlockElementTest{

    /**
     * The language this document currently is in
     * @PHPCR\Locale
     */
    protected $locale;

    /**
     * @PHPCR\Field(type="string", nullable=true, translated=true)
     * @Serializer\Groups({"list","detail"})
     */
    public $caption;
    
    /**
     * @PHPCR\Id()
     * @Serializer\Groups({"list","detail"})
     */
    protected $id;

    /**
     * @PHPCR\Nodename()
     * @Serializer\Groups({"detail"})
     */
    public $key;

    /**
     * @PHPCR\ParentDocument()
     */
    public $parent;
}
```

**Comment by dbu** [comment]
so the data currently in the repository is not translated, but you want to move to translated in attributes, right? can you show the exact command you run? 

i don't understand what you mean by the translator being null in the MetaData - you should enable translation and have everything set up so that you could just store translated documents. the command will then help by pulling the untranslated data into your default language.

**Comment by henningborchers** [comment]
i didn't setup the multilang in the symfony cmf settings:

cmf_core:
  multilang...

Thanks for you help!

**Comment by dbu** [comment]
you are welcome. glad you found the issue.

Am 14.11.2017 6:47 nachm. schrieb "Henning Borchers" <
notifications@github.com>:
