### ISSUE TITLE
about create indexes

### ISSUE THREAD

**Issue by imsheng** [doctrine/phpcr-odm#793]
I don't think it's feasible.
how to improve query speed when  the data is large ( tens of millions)

**Comment by dbu** [comment]
are you using jackalope-doctrine-dbal for the phpcr layer? it does have some indexes, but then all things are stored in the same table. if you query instead of looking up nodes by path, this will probably not scale well to large data sets. that said, if you want to profile that and suggest additional indexes i am happy to look at pull requests.

your other option is to run jackrabbit with jackalope-jackrabbit. the jackrabbit server integrates lucene and is supposed to be much more capable.

either way, avoid having too many nodes as direct children of a single node. too many has been determined in benchmarks to be around 10'000. if you have more children, you should split them up somehow (e.g. instead of /parent/child do /parent/c/child, or use the current date, or a hash... whatever fits your use case).

**Comment by imsheng** [comment]
hi @dbu, I need to develop a CMS,and i have some questions.
1. how to Index the "name" field in xml data?  because the data is large.
```
$qb = $documentManager->createQueryBuilder();
$qb->from()->document('Blog\User', 'u');
$qb->where()->eq()->field('u.name')->literal('dtl');
$query = $qb->getQuery();
```

2.Why use XML instead of JSON?
3.Should these questions be asked at phpcr?  https://github.com/phpcr/phpcr
4.I found some solutions about content management. What do you think? https://github.com/bolt/bolt

**Comment by dbu** [comment]
1. index fields

maybe some of the databases do allow indexes on single xml fields, would need to be tried out.

an other idea that has been discussed but never implemented by anybody is to extend the [database connector](https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php) and have it store some node types in separate tables. you would need to create specific phpcr node types to make that happen however. on phpcr level, the phpcr-odm document classes are not available.

but the easiest would most likely be to use jackalope-jackrabbit as that one is integrating lucene so i assume there are indexes.

another thing is that you should not be searching on thousands of blog posts. PHPCR is useful to build a tree structure, e.g. of year => month => individual blogpost. if you search over everything, there is no point in using PHPCR and it is less performant for search than a solution with doctrine orm and SQL queries on structured data.

2. because at the time we wrote jackalope-doctrine-dbal, not all databases offered native json support. but this should not concern your application never want to interact with the database directly. that would be like opening the files that mysql writes to.

3. PHPCR is only the standard for the content repository. jackalope is the implementation. and phpcr-odm is an object mapper on top of the content repository. its the same people working on all of those, so unless its very specific questions its not that important where you ask ;-)

4. bolt has been around for a while in is used quite a bit afaik. if it can do what you need, then by all means use it, rather than build something yourself from components like phpcr-odm. the components of the content management framework are provided for situations when the needs are too far different from what existing cms can offer. usually you can customize the cms, but there are situations where things are so specific that building something yourself is more efficient than customizing. but building your own cms from these components is a lot more effort than customizing an existing complete cms.
